sudo: required
language: python
python:
  - "2.7"
env:
  # versions of liblouis and liblouisutdml
  - LOUIS_VERSION=debian-jessie UTDML_VERSION=debian-jessie
  - LOUIS_VERSION=head UTDML_VERSION=head # latest from git/hg
matrix:
  allow_failures:
    - env: LOUIS_VERSION=debian-wheezy UTDML_VERSION=debian-wheezy
    - env: LOUIS_VERSION=debian-jessie UTDML_VERSION=debian-wheezy
    - env: LOUIS_VERSION=head UTDML_VERSION=head
install:
  - "sudo apt-get update -qq"
  - "sudo apt-get -y install gettext fontconfig ttf-freefont libxml2-dev texinfo"
  - "pip install reportlab coveralls Babel"
  # install liblouis
  - "git clone https://github.com/liblouis/liblouis && cd liblouis"
  - "if [ $LOUIS_VERSION == 'debian-wheezy' ]; then git checkout liblouis_2_4_1; elif [ $LOUIS_VERSION == 'debian-jessie' ]; then git checkout liblouis_2_5_3; elif [ $LOUIS_VERSION != 'head' ]; then false; fi"
  - "./autogen.sh && ./configure --prefix=/usr --enable-ucs4 && make && sudo make install && cd .."
  # install liblouisutdml
  - "if [ $UTDML_VERSION == 'debian-wheezy' ]; then wget http://http.debian.net/debian/pool/main/libl/liblouisutdml/liblouisutdml_2.2.0.orig.tar.gz && tar xzf liblouisutdml_2.2.0.orig.tar.gz && cd liblouisutdml-2.2.0; fi"
  - "if [ $UTDML_VERSION == 'debian-jessie' ]; then wget https://liblouisutdml.googlecode.com/files/liblouisutdml-2.5.0.tar.gz && tar xzf liblouisutdml-2.5.0.tar.gz && cd liblouisutdml-2.5.0; fi"
  - "if [ $UTDML_VERSION == 'head' ]; then git clone https://github.com/liblouis/liblouisutdml && cd liblouisutdml && ./autogen.sh; fi"
  - "./configure --prefix=/usr CFLAGS='-I/usr/lib/jvm/java-7-oracle/include -I/usr/lib/jvm/java-7-oracle/include/linux' && make && sudo make install && cd .."
script:
  - "PYTHONPATH=`pwd`/lib:$PYTHONPATH LCGDIR=`pwd` make"
  - "PYTHONPATH=`pwd`/lib:`pwd`/liblouis/python:$PYTHONPATH LCGDIR=`pwd` coverage run --source=lib/lcg ./lib/lcg/_test.py"
after_success:
  - "coveralls"
notifications:
  email:
    recipients:
      - lcg-cvs@lists.freebsoft.org
