name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Create virtualenv
        run: |
          python -m venv .venv
          echo "${PWD}/.venv/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install future pygments pillow
          
      - name: Build documentation
        run: make doc

      - name: Deploy to GitHub Pages
        if: ${{ env.ACT != 'true' }}   # skip this step when running locally under act
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html
